framework:
    messenger:
        default_bus: command_bus

        buses:
            command_bus:
                middleware:
                    - doctrine_transaction
            query_bus: ~

        transports:
            sync: 'sync://'

        routing:
            'App\Dashboard\Settings\Application\Find\FindUserPreferencesQuery':
                senders: ['sync']

            'App\Dashboard\Settings\Application\UpdatePreferences\UpdateUserPreferencesCommand':
                senders: ['sync']