controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

dashboard_controllers:
    resource: '../src/Dashboard/'
    type: attribute
    prefix: '/api'
    exclude: '../src/Dashboard/{DependencyInjection,Domain,Application}'

app_home:
    path: /{reactRouting}
    controller: App\Controller\DashboardController::index
    requirements:
        reactRouting: ^(?!api).*$
    methods: [GET]