parameters:
    profile_photos_directory: '%kernel.project_dir%/public/uploads/profile'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Command and Query Handlers
    App\Dashboard\Settings\Application\Find\FindUserPreferencesQueryHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'query_bus' }

    App\Dashboard\Settings\Application\UpdatePreferences\UpdateUserPreferencesCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'command_bus' }

    # Repository
    App\Dashboard\Settings\Infrastructure\Persistence\DoctrineSettingsRepository:
        arguments:
            $connection: '@doctrine.dbal.default_connection'